# Generated by Django 3.2.9 on 2023-06-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos')),
                ('voice', models.FileField(blank=True, null=True, upload_to='media/audios')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('location', models.TextField()),
                ('contact', models.CharField(max_length=16)),
            ],
        ),
    ]
