# Generated by Django 3.2.9 on 2023-06-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
